export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const EXPENSES_ERROR = 'EXPENSES_ERROR';
export const GET_EXPENSES = 'GET_EXPENSES';

export const GET_TOTAL_EXPENSE_COST = 'GET_TOTAL_EXPENSE_COST';


export const GET_TOTAL_DEPOSIT_AMOUNT = 'GET_TOTAL_DEPOSIT_AMOUNT';

export const DEPOSIT_ERROR = 'DEPOSIT_ERROR';

